config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users

  get "/?url=#{:url}" => 'home#index', as: :order_link

  root 'home#index'
  resources :runs do
    resources :orders
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname, :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Feedback to Coffee Together",
      :to => "coffee.bersama@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :store
	has_many :item_details
	validates :store_id, :item_name, presence: true
	validates_associated :store
end

app/models/item_detail.rb
class ItemDetail < ActiveRecord::Base
	belongs_to :item
	has_many :orders, through: :order_item_details
	has_many :order_item_details
	validates :item_id, presence: true
	validates_associated :item
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :run	
	has_many :item_details, through: :order_item_details
	has_many :order_item_details, :dependent => :destroy
	validates :run_id, :user_id, presence: true
	validates_associated :user, :run

end

app/models/order_item_detail.rb
class OrderItemDetail < ActiveRecord::Base
	belongs_to :order
	belongs_to :item_detail
	validates :order_id, :item_detail_id, presence: true
	validates_associated :order, :item_detail
end

app/models/run.rb
class Run < ActiveRecord::Base
	has_many :orders, :dependent => :destroy
	has_many :item_details, through: :orders, join_table: :items
	has_many :items, through: :orders, through: :item_details, join_table: :item_details
	belongs_to :user
	belongs_to :store
	validates :store_id, :user_id, presence: true
	validates_associated :user, :store

  def generate_url
    self.url = SecureRandom.hex(5)
  end
  
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :users, through: :runs
	has_many :runs
	has_many :items
	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stores, through: :runs
	has_many :runs
	has_many :orders
	validates :encrypted_password, presence: true
	validates :email, presence: true, uniqueness: true
	validates :name, presence: true
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!

  def index
  	@runs = Run.where(user_id: current_user).limit(3).order("expired_at DESC")
  	@orders = Order.where(user_id: current_user).limit(3).order("created_at DESC")
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	    if !params[:url].nil?
	  		@run = Run.find_by_url(params[:url])
	  		redirect_to new_run_order_path(@run.id)
	  	end

	end
end
	  

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :authenticate_user!

  def index
    if !params[:url].nil?
      @url = Run.find_by(url: params[:url])
      redirect_to new_run_order_path(@url)
    end
    @runs = Run.all
  end

  def new
  	@run = Run.new
  end

  def create
  	@run = Run.new(run_params)
    @run.user = current_user
    @run.generate_url
  	if @run.save
  	  redirect_to @run
  	else
  	  render 'new'
  	end
  end

  def show
  	set_run
    array = []
    @temp_hash = Hash.new(0)
    @run.orders.each do |order|
      order.item_details.each_with_index do |item_detail, index|
        array << item_detail.item.item_name
        array << item_detail.size
        array << item_detail.temperature
        array << order.user.name
        # array << item_detail.price.ceil
        if index == 0 
          array << order.total_run
        else 
          array << ""
        end
      end
      order.order_item_details.each do |oid|
        @temp_hash[oid.item_detail_id] += oid.quantity.to_i
      end
    end

    @store_array = []
    @temp_hash.each do |k, v|
      @store_array << ItemDetail.find(k).item.item_name
      @store_array << ItemDetail.find(k).size
      @store_array << ItemDetail.find(k).temperature
      @store_array << ItemDetail.find(k).price
      @store_array << v
    end

    @items_array = array.each_slice(5).to_a
    @store_array = @store_array.each_slice(5).to_a
    @datetime = @run.expired_at.strftime("%b %-d, %H:%M")
    @delivertime = (@run.expired_at + 1.hours).strftime("%b %-d, %H:%M")
  end

  def edit
  	set_run
  end

  def update
  	set_run
  	if @run.update_attributes(run_params)
  	  redirect_to @run
  	else
  	  render 'edit'
  	end
  end

  def destroy
  	Run.find(params[:id]).destroy
  	redirect_to '/runs/new'
  end

  

  private

  def set_run
  	@run = Run.find(params[:id])
  end

  def run_params
    if params[:run][:day] == "Today"
      params[:run][:expired_at] = Time.local(params[:run]["expired_time(1i)"],params[:run]["expired_time(2i)"],params[:run]["expired_time(3i)"],params[:run]["expired_time(4i)"],params[:run]["expired_time(5i)"])
    else 
      params[:run][:expired_at] = (Time.local(params[:run]["expired_time(1i)"],params[:run]["expired_time(2i)"],params[:run]["expired_time(3i)"],params[:run]["expired_time(4i)"],params[:run]["expired_time(5i)"]) + (24*60*60))
    end
    ## userid = 1
    # params[:run][:user_id] = 1
    params[:run][:user_id] = current_user.id
    params[:run][:limit] = params[:run][:remaining]
  	params.require(:run).permit(:store_id, :location, :expired_at, :limit, :remaining, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_details_helper.rb
module ItemDetailsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="container">
	  <div class="row">
        <div class="col-lg-12">
	<h2>My Summary</h2>
	<section id="intro" class="dashboard-section">

		<!-- Nav tabs -->
	  <ul class="nav nav-tabs" role="tablist">
	    <li role="presentation" class="active"><a href="#myruns" aria-controls="home" role="tab" data-toggle="tab">My Runs</a></li>
	    <li role="presentation"><a href="#myorders" aria-controls="profile" role="tab" data-toggle="tab">My Orders</a></li>
	  </ul>

		<!-- Tab panes -->
		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="myruns">

				<!-- My Runs -->
				<div class="container-fluid">
					<!-- <h3> My Runs </h3> --><br>

					<% if !(@runs.nil? || @runs.blank?) %>
						<div class="row">
							<% @runs.each do |run| %>
								<div class="col-xs-12 col-sm-4">

									<div class="list-runs">
										<div class="row">
											<div class="col-xs-4 col-sm-4">
												<%= image_tag "starbucks-coffeetogether.png" %>
											</div><!-- end of first column -->

											<div class="col-xs-8 col-sm-8">
												<div class="row">
													<div class="col-xs-12 col-sm-12">
														<%= run.expired_at.strftime("%b %-d") %>
													</div>
												</div>

												<div class="row">
													<div class="col-xs-12 col-sm-12">
														Total Orders: <%= run.orders.count %>
													</div>
												</div>

												<div class="row">
													<div class="col-xs-12 col-sm-12">
														<% @total_earn = run.orders.sum("total_run") - run.orders.sum("total_store") %>
														Earned: RM<%= number_with_precision(@total_earn, :precision => 2) %>
													</div>
												</div>

												<div class="row">
													<div class="col-xs-12 col-sm-12">
														Run ID: <%= run.id %> <br><%= link_to "View Run", run_path(run) %>
													</div>
												</div>
											</div><!-- end of second column -->
										</div><!-- end of this order row -->	
									</div><!-- end of list-orders class -->

								</div><!-- end of main 1,2,3 columns -->
							<% end %>
						</div><!-- end of main row -->
					<% else %>
						<div class="row">
							<div class="col-xs-12 col-sm-12">
								<p> No run yet.<br> Click on 'New Run' to make your first run! </p>
							</div>
						</div>
					<% end %>

					<hr>
					<div class="row">
						<div class="col-xs-12 col-sm-12"> 
							<!-- <button type="button" class="btn btn-default">Default</button> -->
							<%= button_to "New Run", new_run_path, :id => "new-run-btn",
				      :class => "btn btn-primary", :method => :get %>
						</div>
					</div>

				</div>
			</div><!-- end of myruns tab -->

			<div role="tabpanel" class="tab-pane" id="myorders">

				<!-- My Orders -->
				<div class="container-fluid">
					<!-- <h3> My Orders </h3> --><br>

					<% if !(@orders.nil? || @orders.blank?) %>
						<div class="row">
							<% @orders.each do |order| %>
								<div class="col-xs-12 col-sm-4">

									<div class="list-orders">
										<div class="row">
											<div class="col-xs-4 col-sm-4">
												<%= image_tag "starbucks-coffeetogether.png" %>
											</div><!-- end of first column-->

											<div class="col-xs-8 col-sm-8">
												<div class="row">
													<div class="col-xs-12 col-sm-12">
														<%= order.created_at.strftime("%b %-d") %>
													</div>
												</div>

												<div class="row">
													<div class="col-xs-12 col-sm-12">
														Runner Name: <%= order.run.user.name %>
													</div>
												</div>

												<div class="row">
													<div class="col-xs-12 col-sm-12">
														Amount: <%= number_with_precision(order.total_run, :precision => 2) %>
													</div>
												</div>

												<div class="row">
													<div class="col-xs-12 col-sm-12">
														Order ID: <%= order.id %> <br><%= link_to "View Order", run_order_path(order.run, order) %>
													</div>
												</div>
											</div><!-- end of second column -->
										</div><!-- end of this order row -->	
									</div><!-- end of list-orders class -->

								</div><!-- end of main 1,2,3 columns -->
							<% end %>
						</div><!-- end of main row -->
					<% else %>
						<div class="row">
							<div class="col-xs-12 col-sm-12">
								<p> No order yet. </p>
							</div>
						</div>
					<% end %>

				</div>
			</div><!-- end of myorders tab -->

		</div><!-- tabpanel-->

	</section>

	            </div>
      </div>
      
</div>