config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users

  get "/?url=#{:url}" => 'home#index', as: :order_link

  root 'home#index'
  resources :runs do
    resources :orders
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname, :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Feedback to Coffee Together",
      :to => "coffee.bersama@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :store
	has_many :item_details
	validates :store_id, :item_name, presence: true
	validates_associated :store
end

app/models/item_detail.rb
class ItemDetail < ActiveRecord::Base
	belongs_to :item
	has_many :orders, through: :order_item_details
	has_many :order_item_details
	validates :item_id, presence: true
	validates_associated :item
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :run	
	has_many :item_details, through: :order_item_details
	has_many :order_item_details, :dependent => :destroy
	validates :run_id, :user_id, presence: true
	validates_associated :user, :run

end

app/models/order_item_detail.rb
class OrderItemDetail < ActiveRecord::Base
	belongs_to :order
	belongs_to :item_detail
	validates :order_id, :item_detail_id, presence: true
	validates_associated :order, :item_detail
end

app/models/run.rb
class Run < ActiveRecord::Base
	has_many :orders, :dependent => :destroy
	has_many :item_details, through: :orders, join_table: :items
	has_many :items, through: :orders, through: :item_details, join_table: :item_details
	belongs_to :user
	belongs_to :store
	validates :store_id, :user_id, presence: true
	validates_associated :user, :store

  def generate_url
    self.url = SecureRandom.hex(5)
  end
  
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :users, through: :runs
	has_many :runs
	has_many :items
	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stores, through: :runs
	has_many :runs
	has_many :orders
	validates :encrypted_password, presence: true
	validates :email, presence: true, uniqueness: true
	validates :name, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	    if !params[:url].nil?
	  		@run = Run.find_by_url(params[:url])
	  		redirect_to new_run_order_path(@run.id)
	  	end

	end
end
	  

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :authenticate_user!

  def index
    if !params[:url].nil?
      @url = Run.find_by(url: params[:url])
      redirect_to new_run_order_path(@url)
    end
    @runs = Run.all
  end

  def new
  	@run = Run.new
  end

  def create
  	@run = Run.new(run_params)
    @run.user = current_user
    @run.generate_url
  	if @run.save
  	  redirect_to @run
  	else
  	  render 'new'
  	end
  end

  def show
  	set_run
    array = []
    @temp_hash = Hash.new(0)
    @run.orders.each do |order|
      order.item_details.each_with_index do |item_detail, index|
        array << item_detail.item.item_name
        array << item_detail.size
        array << item_detail.temperature
        array << order.user.name
        # array << item_detail.price.ceil
        if index == 0 
          array << order.total_run
        else 
          array << ""
        end
      end
      order.order_item_details.each do |oid|
        @temp_hash[oid.item_detail_id] += oid.quantity.to_i
      end
    end

    @store_array = []
    @temp_hash.each do |k, v|
      @store_array << ItemDetail.find(k).item.item_name
      @store_array << ItemDetail.find(k).size
      @store_array << ItemDetail.find(k).temperature
      @store_array << ItemDetail.find(k).price
      @store_array << v
    end

    @items_array = array.each_slice(5).to_a
    @store_array = @store_array.each_slice(5).to_a
    @datetime = @run.expired_at.strftime("%b %-d, %H:%M")
    @delivertime = (@run.expired_at + 1.hours).strftime("%b %-d, %H:%M")
  end

  def edit
  	set_run
  end

  def update
  	set_run
  	if @run.update_attributes(run_params)
  	  redirect_to @run
  	else
  	  render 'edit'
  	end
  end

  def destroy
  	Run.find(params[:id]).destroy
  	redirect_to '/runs/new'
  end

  

  private

  def set_run
  	@run = Run.find(params[:id])
  end

  def run_params
    if params[:run][:day] == "Today"
      params[:run][:expired_at] = Time.local(params[:run]["expired_time(1i)"],params[:run]["expired_time(2i)"],params[:run]["expired_time(3i)"],params[:run]["expired_time(4i)"],params[:run]["expired_time(5i)"])
    else 
      params[:run][:expired_at] = (Time.local(params[:run]["expired_time(1i)"],params[:run]["expired_time(2i)"],params[:run]["expired_time(3i)"],params[:run]["expired_time(4i)"],params[:run]["expired_time(5i)"]) + (24*60*60))
    end
    ## userid = 1
    # params[:run][:user_id] = 1
    params[:run][:user_id] = current_user.id
    params[:run][:limit] = params[:run][:remaining]
  	params.require(:run).permit(:store_id, :location, :expired_at, :limit, :remaining, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_details_helper.rb
module ItemDetailsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_form.html.erb
<div class= 'container'>
  <div class= 'row'>
  	<div class= 'col-md-6 col-md-offset-3'>
  		<div class= 'text-center'><h3><%= yield(:header) %></h3></div>
		<%= bootstrap_form_for(@run) do |f| %>
			<%= f.collection_select(:store_id, Store.all, :id, :name) %>
			<%= f.select :day, ["Today", "Tomorrow"], selected: "Today" %>
			<%= f.time_select :expired_at, minute_step: 15, selected: Time.now %>
			<%= f.text_field :remaining, value: 10, label: "Max orders to take" %>
			<%= f.submit yield(:submit), class: 'btn btn-primary' %>
		<% end %>
	</div> 
  </div>
</div>

app/views/home/index.html.erb
<!-- Header -->
<a name="about"></a>
<div class="intro-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <!-- <div class="col-lg-12" style="background-color: rgba(0,0,0,0.2);"> -->
        <div class="intro-message">
          <h1>Coffee Together</h1>
          <h3>Together We Get Caffeinated</h3>
          <!-- <hr class="intro-divider"> -->
          <!-- <ul class="list-inline intro-social-buttons">
            <li>
              <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
            </li>
            <li>
              <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
            </li>
            <li>
              <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
            </li>
          </ul> -->
        </div>
      </div>
    </div>
  </div>
    <!-- /.container -->
</div>

<!-- Page Content -->
<a  name="services"></a>
<div class="content-section-a">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-sm-6">
        <!-- <hr class="section-heading-spacer"> -->
        <div class="clearfix"></div>
        <h2 class="section-heading">Be a RUNNER now & <br>DELIVER coffee to your friends...</h2>
        <p class="lead">
          <%= link_to "Register", new_user_registration_path %> and be part of our community<br><br>
          Step 1: Create a <%= link_to "New Run", new_run_path %><br>
          Step 2: Broadcast your run and invite friends to order<br>
          Step 3: Make your coffee run and deliver! 
        </p>
      </div>
      <div class="col-lg-5 col-lg-offset-2 col-sm-6">
        <img class="img-responsive" src="../../assets/coffeebtm1-beans.jpg" alt="">
      </div>
    </div>
  </div>
  <!-- /.container -->
</div>
<!-- /.content-section-a -->

<div class="content-section-b">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
        <!-- <hr class="section-heading-spacer"> -->
        <div class="clearfix"></div>
        <h2 class="section-heading">COFFEE LOVERS get connected & ORDER your coffee...</h2>
        <p class="lead">
          <%= link_to "Register", new_user_registration_path %> and be part of our community<br><br>
          Step 1: Receive an invite from runner<br>
          Step 2: Click on the invite link and place your order! 
        </p>
      </div>
      <div class="col-lg-5 col-sm-pull-6  col-sm-6">
          <img class="img-responsive" src="../../assets/coffeebtm2-holland.jpg" alt="">
      </div>
    </div>
  </div>
  <!-- /.container -->
</div>
<!-- /.content-section-b -->

<div class="content-section-a">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-sm-6">
        <!-- <hr class="section-heading-spacer"> -->
        <div class="clearfix"></div>
        <h2 class="section-heading">Our next episodes</h2>
        <p class="lead">Breakfast run? Tea Time run? </p>
        <p class="lead">What would you like your friend to deliver next?<br>Any feedback to share with us? <br><%= link_to "Feedback Now", new_contact_path %> or <%= mail_to "coffee.bersama@gmail.com", "Email Us" %>
        </p>
      </div>
      <div class="col-lg-5 col-lg-offset-2 col-sm-6">
        <img class="img-responsive" src="../../assets/coffeebtm3-macaroons.jpg" alt="">
      </div>
    </div>
  </div>
  <!-- /.container -->
</div>
<!-- <a  name="contact"></a>

<div class="banner">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
          <h2>Connect to Start Bootstrap:</h2>
      </div>
      <div class="col-lg-6">
        <ul class="list-inline banner-social-buttons">
          <li>
            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
          </li>
          <li>
            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
          </li>
          <li>
            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
          </li>
        </ul>
      </div>
    </div>
  </div> -->
<!-- /.container -->
<!--</div> -->

<!-- 4-Aug Comment and move the footer section to application.html.erb-->
<!-- Footer -->
<!-- <footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline">
          <li>
            <a href="#">Home</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="#about">About</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="#services">Services</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="#contact">Contact</a>
          </li>
        </ul>
        <p class="copyright text-muted small" align="center">Copyright &copy; Coffee Together 2015. All Rights Reserved</p>
      </div>
    </div>
  </div>
</footer> -->