config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users

  get "/?url=#{:url}" => 'home#index', as: :order_link

  root 'home#index'
  resources :runs do
    resources :orders
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/run.rb
class Run < ActiveRecord::Base
	has_many :orders, :dependent => :destroy
	has_many :item_details, through: :orders, join_table: :items
	has_many :items, through: :orders, through: :item_details, join_table: :item_details
	belongs_to :user
	belongs_to :store
	validates :store_id, :user_id, presence: true
	validates_associated :user, :store

  def generate_url
    self.url = SecureRandom.hex(5)
  end
  
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :authenticate_user!

  def index
    if !params[:url].nil?
      @url = Run.find_by(url: params[:url])
      redirect_to new_run_order_path(@url)
    end
    @runs = Run.all
  end

  def new
  	@run = Run.new
  end

  def create
  	@run = Run.new(run_params)
    @run.user = current_user
    @run.generate_url
  	if @run.save
  	  redirect_to @run
  	else
  	  render 'new'
  	end
  end

  def show
  	set_run
    array = []
    @temp_hash = Hash.new(0)
    @run.orders.each do |order|
      order.item_details.each_with_index do |item_detail, index|
        array << item_detail.item.item_name
        array << item_detail.size
        array << item_detail.temperature
        array << order.user.name
        # array << item_detail.price.ceil
        if index == 0 
          array << order.total_run
        else 
          array << ""
        end
      end
      order.order_item_details.each do |oid|
        @temp_hash[oid.item_detail_id] += oid.quantity.to_i
      end
    end

    @store_array = []
    @temp_hash.each do |k, v|
      @store_array << ItemDetail.find(k).item.item_name
      @store_array << ItemDetail.find(k).size
      @store_array << ItemDetail.find(k).temperature
      @store_array << ItemDetail.find(k).price
      @store_array << v
    end

    @items_array = array.each_slice(5).to_a
    @store_array = @store_array.each_slice(5).to_a
    @datetime = @run.expired_at.strftime("%b %-d, %H:%M")
    @delivertime = (@run.expired_at + 1.hours).strftime("%b %-d, %H:%M")
  end

  def edit
  	set_run
  end

  def update
  	set_run
  	if @run.update_attributes(run_params)
  	  redirect_to @run
  	else
  	  render 'edit'
  	end
  end

  def destroy
  	Run.find(params[:id]).destroy
  	redirect_to '/runs/new'
  end

  

  private

  def set_run
  	@run = Run.find(params[:id])
  end

  def run_params
    if params[:run][:day] == "Today"
      params[:run][:expired_at] = Time.local(params[:run]["expired_time(1i)"],params[:run]["expired_time(2i)"],params[:run]["expired_time(3i)"],params[:run]["expired_time(4i)"],params[:run]["expired_time(5i)"])
    else 
      params[:run][:expired_at] = (Time.local(params[:run]["expired_time(1i)"],params[:run]["expired_time(2i)"],params[:run]["expired_time(3i)"],params[:run]["expired_time(4i)"],params[:run]["expired_time(5i)"]) + (24*60*60))
    end
    ## userid = 1
    # params[:run][:user_id] = 1
    params[:run][:user_id] = current_user.id
    params[:run][:limit] = params[:run][:remaining]
  	params.require(:run).permit(:store_id, :location, :expired_at, :limit, :remaining, :user_id)
  end

end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/_form.html.erb
<div class= 'container'>
  <div class= 'row'>
  	<div class= 'col-md-6 col-md-offset-3'>
  		<div class= 'text-center'><h3><%= yield(:header) %></h3></div>
		<%= bootstrap_form_for(@run) do |f| %>
			<%= f.collection_select(:store_id, Store.all, :id, :name) %>
			<%= f.text_field :location, label: "Deliver to", placeholder:"enter office location, building or etc."%>
			<%= f.select :day, ["Today", "Tomorrow"], selected: "Today" %>
			<%= f.time_select :expired_time, ampm: true, selected: Time.zone.now + 60.minutes %>
			Remarks: Once expired, no more new order will be taken. Expected delivery time will be defaulted as 1 hour after this expiry.<br><br>
			<%= f.text_field :remaining, value: 10, label: "Maximum order items to take" %>
			<%= f.submit yield(:submit), class: 'btn btn-primary' %>
		<% end %>
	</div> 
  </div>
</div>

app/views/runs/edit.html.erb
<%= provide(:submit, "Edit Run") %>
<%= provide(:header, "Edit Run") %>
<%= render 'form' %>

app/views/runs/index.html.erb
<% @runs.each do |run| %>
  <p>Store ID: <%= run.store_id %></p>
  <p>Expired At: <%= run.expired_at %></p>
<% end %>

app/views/runs/new.html.erb
<%= provide(:submit, "Run!")%>
<%= provide(:header, "New Run")%>
<%= render 'form' %>

app/views/runs/show.html.erb
<div id="ordersummary" class= 'container'>
	<h2>Orders Summary</h2>
	<div class='row'>
		<div class='col-md-6'>
			<h4>Store: <strong><%= @run.store.name %></strong></h4>
			<h4>Remaining of <strong><%= @run.remaining %> order items </strong></h4>
			<% if (Time.now - @run.expired_at) >= 0 %>
				<h4 style="color:darkred">Run expired at <strong><%= @datetime %></strong></h4>
				<!-- <h4 style= 'color: red;'>Run expired!</h4> -->
			<% else %>
				<h4>Run expired at <strong><%= @datetime %></strong></h4>
			<% end %>
		</div>

		<div class='col-md-4'>
			<textarea id= 'message-order' rows= '7' cols= '40'>Hi guys! <%= @run.user.name %> here. I am going to <%= @run.store.name %>. Let me know if you need anything by <%= @datetime %> (Deliver to: <%= @run.location %> at around <%= @delivertime %>). Click link to order => https://coffeetogether.herokuapp.com/?url=<%=@run.url %>
			</textarea>
			<div class= 'span3'>
				<button class='btn btn-primary btn-run' data-clipboard-target='message-order' data-clipboard-text='Default clipboard text from attribute' id='order_clip_button' title='Click me to copy to clipboard.'>
			    	Quick Copy Broadcast Message
			  	</button>
			  After copied, you may paste it to your Whatsapp or Slack group and send it as order invites. View all the orders from the Order Summary.<br><br>
		  </div>		
		</div>
	</div>

	<div>
		<ul class="nav nav-tabs" id= 'summary-tab'>
		  <li class="active"><a data-toggle="tab" href="#store">Order Summary</a></li>
		  <li><a data-toggle="tab" href="#order">Order Details</a></li>
		</ul>
	</div>

	<div class="tab-content">
	  <div id="store" class="tab-pane fade in active">
	    <div id="store-summary" class= 'container-fluid table-responsive '>
				<!-- <h3>Order Summary</h3> --><br>
				<div class= 'row hidden-xs hidden-sm' style= 'font-weight: bold'>
					<div class= 'col-md-2 text-left'>ITEM NAME</div>
					<div class= 'col-md-2'>SIZE</div>
					<div class= 'col-md-2'>HOT/COLD</div>
					<div class= 'col-md-2'>UNIT PRICE (RM)</div>
					<div class= 'col-md-2'>QUANTITY</div>
				</div><hr>
				<% @store_array.each do |row| %>
					<div class='row'>
						<% row.each_with_index do |value, index| %>
							<% if index == 0 %>
								<div class= 'col-md-2 col-xs-12 text-left'>
									<%= value %>
								</div>
							<% end %>
							<% if index == 1 || index == 2 || index == 3 %>
								<div class= 'col-md-2 col-xs-3'>
									<%= value %>
								</div>
							<% end %>
							<% if index == 4 %>
								<div class= 'col-md-2 col-xs-3'>
									<strong><%= value %></strong>
								</div>
							<% end %>
						<% end %>
					</div>
					<hr>
				<% end %>
				<!--
				<table class= 'table table-striped'>
					<thead>
					  <tr>
					  	<th>Item Name</th>
					  	<th>Size</th>
					  	<th>Hot/Cold</th>
					  	<th>Price(RM)</th>
					  	<th>Quantity</th>
					  </tr>
					</thead>
					 <tbody>
						<% @store_array.each do |row|%>
						  <tr>
						  	<% row.each do |v| %>
						  	  <td><%= v %></td>
						  	<% end %>
						  </tr>
						<% end %>
					</tbody>
				</table>

				<div class= 'row'>
					<div class= 'col-xs-2'>Item Name</div>
					<div class= 'col-xs-2'>Size</div>
					<div class= 'col-xs-2'>Hot/Cold</div>
					<div class= 'col-xs-2'>Price(RM)</div>
					<div class= 'col-xs-2'>Quantity</div>
				</div>
				-->
				<!-- XS COLUMN -->
				<!--
				<% @store_array.each do |row| %>
					<div class='row'>
						<% row.each do |v| %>
							<div class= 'col-xs-2'><%= v %></div>
						<% end %>
					</div>
				<% end %>
				-->
			</div>
		
			<div class='row'>
				<div class= 'col-md-offset-8 col-md-4'>
					<div style= 'font-weight: bold'>
						<div>TOTAL PAY TO STORE </div>
						<div style= 'font-size: 24px'><u><mark>RM <%= number_with_precision(@run.orders.sum("total_store").round(2), precision: 2)%></mark></u>
						</div>
					</div>
				</div>
			</div>
			<hr>
			<div class='row'>
				<div class= 'col-md-2'>
					<%#= link_to "Edit Run".html_safe, edit_run_path(@run), class: 'btn btn-success btn-block' %> 
					<%= link_to "Cancel Run".html_safe, @run, method: :delete, data: {confirm: "All existing orders will be removed. Are you sure to cancel the run?"}, class: 'btn btn-primary btn-block' %>
				</div>
			</div>

	  </div>

	  <div id="order" class="tab-pane fade">
	  	<div id="store-details" class= 'container-fluid table-responsive '>
	  		<!--<div class= 'order-summary table-responsive'>-->
	  		<!-- <h3>Order Details</h3> --><br>
	  		<!--
	  		<table class= 'table table-striped'>
	        	<thead>
	        		<tr>
	        			<th>Item Name</th>
	        			<th>Size</th>
	        			<th>Hot/Cold</th>
	        			<th>User</th>
	        			<th>Amount To Collect (RM)</th>
	        		</tr>
	        	</thead>
	        	<tbody>
	        		<% @items_array.each do |row| %>
	        			<tr>
	        				<% row.each do |v| %>
	        				  <td><%= v %></td>
	        				<% end %>
	        			</tr>
	        		<% end %>
	        	</tbody>
	        </table> 
	    	-->

		    <!-- XS COLUMN-->
	      <div class= 'row hidden-xs hidden-sm' style= 'font-weight: bold'>
					<div class= 'col-md-2 text-left'>ITEM NAME</div>
					<div class= 'col-md-2'>SIZE</div>
					<div class= 'col-md-2'>HOT/COLD</div>
					<div class= 'col-md-2'>ORDERED BY</div>
					<div class= 'col-md-2'>COLLECT (RM)</div>
				</div><hr>
	      <% @items_array.each do |row| %>
					<div class='row'>
						<% row.each_with_index do |value, index| %>
							<% if index == 0 %>
								<div class= 'col-md-2 col-xs-12 text-left'>
									<%= value %>
								</div>
							<% end %>
							<% if index == 1 || index == 2 || index == 3 || index == 4 %>
								<div class= 'col-md-2 col-xs-3'>
									<%= value %>
								</div>
							<% end %>
						<% end %>
					</div>
					<hr>
				<% end %>
			</div>

			<div class='row'>
				<div class= 'col-md-offset-8 col-md-4'>
					<!-- <div class= 'pull-right' style= 'font-weight: bold'> -->
					<div style= 'font-weight: bold'>
						<div >TOTAL TO COLLECT</div>
						<div style= 'font-size: 24px'> <u><mark>RM <%= number_with_precision(@run.orders.sum("total_run").round(2), precision: 2) %></mark></u>
						</div>
					</div>
				</div>
			</div>
			<hr>
			<div class='row'>
				<div class= 'col-md-2'>
					<%#= link_to "Edit Run".html_safe, edit_run_path(@run), class: 'btn btn-success btn-block' %>
					<%= link_to "Cancel Run".html_safe, @run, method: :delete, data: {confirm: "All existing orders will be removed. Are you sure to cancel the run?"}, class: 'btn btn-primary btn-block' %>
				</div>
			</div>
	  </div>

	</div>
</div>

<script>
  var linkClip = new ZeroClipboard($("#order_clip_button"));
</script>